version: '3.7'

services:
  parser:
    image: halushko/vytiag-pdf-parser:latest
    environment:
      BOT_TOKEN: <input bot token here>
      BOT_TRUSTED_USERS: <comma separated user IDs>
      BUILD_ADDRESSES: "Каблукова Академіка;Скакуна Віталія"
    restart: always
    container_name: "parser"