version: '3.7'

x-common-variables: &common-variables
  RABBITMQ_DEFAULT_USER: rabbit_user
  RABBITMQ_DEFAULT_PASS: rabbit_pswrd
  RABBIT_PORT: 5672
  RABBIT_IP: 10.11.255.254

  BOT_TOKEN: <input bot token here>
  BOT_NAME: <input bot name here>
  BOT_TRUSTED_USERS: <comma separated user IDs>

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    container_name: "rabbit"
    restart: always
    environment: *common-variables
    networks:
      parser_private_network:
        ipv4_address: 10.11.255.254
    ports:
      - 5672:5672
      - 15672:15672
  parser:
    image: halushko/vytiag-pdf-parser:latest
    environment: *common-variables
    restart: always
    container_name: "parser"
    networks:
      parser_private_network:
        ipv4_address: 10.11.0.3
    depends_on:
      - rabbitmq
networks:
  parser_private_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.0.0/16